[package]
name = "promql"
description = "PromQL parser"
version = "0.2.0"
authors = ["vthriller <unixway.drive+rs@gmail.com>"]
license = "Apache-2.0"

[dependencies]

[dependencies.nom]
version = "^3.2"
features = ["verbose-errors"]
