[package]
name = "promql"
description = "PromQL parser"
version = "0.1.0"
authors = ["vthriller <unixway.drive+rs@gmail.com>"]

[dependencies]

[dependencies.nom]
version = "^3.2"
features = ["verbose-errors"]
